"""extended board code attribute

Revision ID: 10460765f337
Revises: 57a99337e843
Create Date: 2021-11-03 16:17:19.310762

"""

# revision identifiers, used by Alembic.
revision = '10460765f337'
down_revision = '57a99337e843'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'code',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###
