#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.


# revision identifiers, used by Alembic.
revision = 'b98819997377'
down_revision = 'f28f3f4494b3'

from alembic import op
import iotronic.db.sqlalchemy.models
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('lr_version',
                                      sa.String(length=20), nullable=True))
    op.add_column('boards',
                  sa.Column('connectivity',
                            iotronic.db.sqlalchemy.models.JSONEncodedDict(),
                            nullable=True))
    # ### end Alembic commands ###
